### PR TITLE
Added Govinda to SFDC STOP Contributor

### PR DESCRIPTION
**Pull request by govindagaikwad**
My First PR.

### CODE REVIEW

**Comment by rahulmalhotra** [comment]
Congratulations @govindagaikwad for your first PR. It is perfect..!! Hope you enjoyed working on the codelab 😄

**Comment by govindagaikwad** [comment]
Hi Rahul Sir,

If having any study material of lightning component.please let me know.

Thank you,
Govinda Gaikwad

**Comment by rahulmalhotra** [comment]
Hi Govinda,

If you want to learn from basics, you can check this out for aura:- https://www.youtube.com/playlist?list=PLuL63vr-9xHyUBXPzHVvr08ayU5N06YoS

and for LWC:- https://www.youtube.com/playlist?list=PLuL63vr-9xHyaEARj8crQe3v2TBQa_Cs8

**Comment by govindagaikwad** [comment]
Thanks a lot for sharing.

Thanks & Regards,
Govinda Gaikwad

**Pull request merged**
