### PR TITLE
Rajasekhar cotributed

### PR DESCRIPTION
**Pull request by raja10061987**
this is my first pull request

### CODE REVIEW

**Comment by raja10061987** [comment]
yes your PR looking good.

**Comment by raja10061987** [comment]
don't have write access. so cannot able to do pull request

**Comment by rahulmalhotra** [comment]
Hi @raja10061987 there is a lot of additional metadata with this PR. Please remove that so I can merge it. Your PR should only contain changes related to `SFDCStopTeamController.cls`

**Comment by raja10061987** [comment]
Hi @rahulmalhotra cann't able to delete unwanted files. please suggest how to delete them.

**Comment by rahulmalhotra** [comment]
I think it's easier if we close this PR. You can clone the repo again, make sure that `.sf` folder is in `.gitignore`, make only the required changes and commit them.

**Pull request closed without merging**
